version: "3.8"

services:

  # mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - "db-vol:/var/lib/mysql:delegated"

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      - PMA_HOST: mysql
      - MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8082:8082"
    restart: always

  # WordPress
  wordpress:
    image: wordpress:5-fpm
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${DB_USER}
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    restart: always
    volumes:
      - "./site:/var/www/html:cached"

  # nginx
  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    environment:
      - "NGINX_ENVSUBST_TEMPLATE_SUFFIX=.conf"
      - "DOMAIN=${DOMAIN}"
      - "LIVE_DOMAIN=${LIVE_DOMAIN}"
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - "./config/nginx:/etc/nginx/templates"
      - "./config/certs:/etc/certs"
      - "./site:/var/www/html:cached"

volumes:
  db-vol: